default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jiffy_development

test:
  <<: *default
  database: jiffy_test

production:
  <<: *default
  database: jiffy_production
  # username: jiffy
  # password: <%= ENV['JIFFY_DATABASE_PASSWORD'] %>
